### ISSUE TITLE
Request for Gmail and Facebook login options

### ISSUE THREAD

**Issue by basicvisual** [expo-community/expo-firebase-starter#20]
A great repository collection ,is it possible to extend to google and facebook login as well?

**Comment by TiagoSeverino** [comment]
You can checkout how I implemented fb login in my repository: https://github.com/TiagoSeverino/expo-firebase-template/commit/26978a164ab359d9132bc308708370640697c659

**Comment by basicvisual** [comment]
oh wow , thank you , I will check it out . We do need to some additional configurations on the friebase side right ? Do you have the documentation for it ?

**Comment by TiagoSeverino** [comment]
You need to get a FACEBOOK_APP_ID

Here's the official expo documentation: https://docs.expo.io/guides/using-firebase/#listening-for-authentication

**Comment by basicvisual** [comment]
thanks is the implementation done here ? https://github.com/TiagoSeverino/expo-firebase-starter

**Comment by TiagoSeverino** [comment]
It was done in this repository: https://github.com/TiagoSeverino/expo-firebase-template/

You can view the what I changed to add fb login in this pull request: https://github.com/TiagoSeverino/expo-firebase-template/commit/26978a164ab359d9132bc308708370640697c659

**Comment by basicvisual** [comment]
@TiagoSeverino  , another related question , have you been able to write the /push the data into the realtime database ?

**Comment by TiagoSeverino** [comment]
@basicvisual I've only played with Firestore, but I guess it should be similar to realtime database.

**Comment by basicvisual** [comment]
@TiagoSeverino oh ok .I am trying to write to the database on login . Like when the user logs in , it is directly written to the realtime database . I am wondering where should that be implemented. Is it the home screen or firebase? if you have managed successfully then please let me know .

**Comment by TiagoSeverino** [comment]
@basicvisual not sure exactly what you want to do, but in my opinion you should implement it on handleOnLogin @ LoginScreen.js

**Comment by basicvisual** [comment]
@TiagoSeverino  thank you ! I had a question. If i wanted to create another screen lets say Statistics.js under screens and move the logout function there . I was wondering what changes have to be done ? so basically 
onPress={() => navigation.navigate('Statistics')}   . So the page sequecne would be login->Statistics -> Home

**Comment by amandeepmittal** [comment]
I am closing this issue @basicvisual as it is now out of scope in terms of features this boilerplate has.
