### ISSUE TITLE
screens > HomeScreen function attributes

### ISSUE THREAD

**Issue by lxs** [expo-community/expo-firebase-starter#25]
Observing a warning in Xcode Simulator when running your project code:

`"React.createElement: type is invalid -- expected a string (for build-in components) or a class/function (for composite components) but got: undefined.`

Uploaded screen-shot of Simulator warning: https://ibb.co/J2NYFdq 
(available to view for 2 weeks from today, then image file shall be automatically deleted by hosting site).

Did not observe a typo, nor any import mistake; the invoking function call has similar style as used for other screens that do not demonstrate similar warning. As such, this appears to be a single occurrence in the project.

-//-

Furthermore, a minor query:
What is your logic behind not including navigation in this function definition?

your code: 
`export default function HomeScreen () {`
vs
`export default function HomeScreen(**{ navigation }**) {`

Is this because, as the HomeScreen.js has been implemented, there is no use of navigation within the default function?
Observed this difference when contrasting the implementation of other screens - yet each of these invokes another screen, and therefore has a practical requirement for navigation attribute to be passed into the default function for the screen.

|Thank you |

**Comment by amandeepmittal** [comment]
> Observing a warning in Xcode Simulator when running your project code:
> 
> `"React.createElement: type is invalid -- expected a string (for build-in components) or a class/function (for composite components) but got: undefined.`
> 

Thanks for reporting this @lxs, let me verify it and get back to you.

>Is this because, as the HomeScreen.js has been implemented, there is no use of navigation within the default function?
Observed this difference when contrasting the implementation of other screens - yet each of these invokes another screen, and therefore has a practical requirement for navigation attribute to be passed into the default function for the screen.

Yes, as you said there is no use of `navigation` prop or in the `HomeScreen.js` for  this template.

**Comment by amandeepmittal** [comment]
Hey @lxs, I could not simulate issue/warning you were having. I tried on Expo client on real device as well as simulator. Are you still having it?

**Comment by lxs** [comment]
Apologies for delayed response. Did not observe notification of your reply.

Yes, I still see this warning message relating to HomeScreen.
This has been observed in the simulator on Mac. I shall repeat with real device and report back here.

**Comment by amandeepmittal** [comment]
No worries @lxs. Let me know what happens after the testing. Also, I am assuming you are on the latest release of this repo.

**Comment by amandeepmittal** [comment]
Hey @lxs I am closing this issue for now. If you are still facing the issue, let me know, may be we can collaborate to discuss it.
