### ISSUE TITLE
Home.navigationOptions dosn't work with components being passed through firebase context

### ISSUE THREAD

**Issue by jim-alexander** [expo-community/expo-firebase-starter#3]
changing navigation options when passing the component though the context api dosn't work.

`
Apps.navigationOptions = {
  title: 'Apps'
}
export default withFirebaseHOC(Apps)
`

**Comment by amandeepmittal** [comment]
Hi @jim-alexander, can you please share the complete snippet?

**Comment by jim-alexander** [comment]
If i have a functional component that I pass though the firebaseHOC as follows: 

```
const Home = () => {
    return (
        <View>
            <Text>This is my home page!</Text>
        </View>
    )
}


export default withFirebaseHOC(Home)
```

Typically you can add navigation options by adding the following before export.

`
Home.navigationOptions = {
    title: 'Home Page'
}
`

But this dosn't work when exporting default withFirebaseHoc

**Comment by amandeepmittal** [comment]
I think, this does not have anything to do with FirbaseHOC. Please check nesting of Stack and Tabs [here](https://github.com/react-navigation/react-navigation/issues/5710).

**Comment by iamwill123** [comment]
@jim-alexander I believe this will help as I had this same question and issue. I did some digging and adapted some code which I referenced below, into this:

context.js:
`
import React, { createContext } from 'react';
import hoistNonReactStatics from 'hoist-non-react-statics';

const FirebaseContext = createContext({});

export const FirebaseProvider = FirebaseContext.Provider;

export const FirebaseConsumer = FirebaseContext.Consumer;

export const withFirebaseHOC = Component => {
  const Wrapper = props => {
    return (
      <FirebaseConsumer>
        {state => <Component {...props} firebase={state} />}
      </FirebaseConsumer>
    );
  };
  hoistNonReactStatics(Wrapper, Component);
  return Wrapper;
};
`
The key was coping the static methods over using the hoist-non-react-statics package.

Ref: 
https://kentcdodds.com/blog/mixing-component-patterns
https://www.npmjs.com/package/hoist-non-react-statics
https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over

Best,
Will

**Comment by amandeepmittal** [comment]
Hey @iamwill123 

Apologies for getting back to you on so late. Feel free to submit a PR on this. However, do note that, in future, I will be upgrading react-navigation to v5 and thus, the firebase auth methods consumption might change.

A big thank you for the above solution ❤️
