### ISSUE TITLE
Stuck on splash screen

### ISSUE THREAD

**Issue by ceid1987** [expo-community/expo-firebase-starter#30]
Hello,

I created my project using your template (latest release SDK 40), I renamed the firebase config file to firebaseConfig and replaced everything with my own project's information. I didn't change anything else in the code. When I try running the app using android studio and my own phone with the expo app as well, I get stuck on the splash screen. The solutions I found online were either outdated or did not work at all.

**Comment by amandeepmittal** [comment]
Hey @ceid1987 is it working now?

Have you updated the Expo client on the various devices and simulators you are trying to run this app?

**Comment by amandeepmittal** [comment]
Hey @ceid1987 I am closing this issue, if you are still having problems, let me know.
