### ISSUE TITLE
correct use of context

### ISSUE THREAD

**Issue by byHippo** [expo-community/expo-firebase-starter#32]
I'm trying to use the user context, but I don't understand the exact working of this one. I want to get the UID of a user with the context but I don't know if it is possible.

**Comment by amandeepmittal** [comment]
Hey @byHippo 

The `user` context stores the current authenticated user object from Firebase with Email authentication.

The JSON object looks like the following: 

```json
{
    "displayName": null,
    "email": "a@a.com",
    "emailVerified": false,
    "isAnonymous": false,
    "metadata": [Object],
    "phoneNumber": null,
    "photoURL": null,
    "providerData": [Array],
    "providerId": "firebase",
    "uid": "Bcb7dubfsEPkHfTHmINSvuJ50Hy2"
  }
```

Using the React hook `useContext` you can access the value of the `user` object and then any of its properties. For example, to access UID, you'll have to do something like:

```js
// import useContext from React
import React, {useContext} from 'react';

// in a function component
const { user } = useContext(AuthenticatedUserContext);

// then you can use it like, if the user is authenticated
useEffect(() => {
  if(user !== null){
    console.log(user.uid);
  }
}, []);
```

**Comment by byHippo** [comment]
Thanks, that works

**Comment by amandeepmittal** [comment]
Great. I am closing this issue now.
