### ISSUE TITLE
Not working after installing expo-development-client

### ISSUE THREAD

**Issue by ushyDev** [expo-community/expo-firebase-starter#70]
After installing the project from **expo-firebase-starter**, I added **eas-cli** and **expo-development-client** to the project. When I build the app through eas and release to testflight the app crashes after showing the loading screen. 
I have tested this several times by creating new projects and there is always the same error. It happens only after installing expo-development-client, but when I create new application using **expo init** and add expo-development-client everything works fine.

Steps to reproduction:
1. Create new app `npx create-react-native-app --template https://github.com/expo-community/expo-firebase-starter`
2. Add EAS CLI `npm install -g eas-cli`
3. Add `expo install expo-dev-client`
4. Build app with EAS for siimulator `eas build -p ios --profile preview`
5. Open app in simulator

package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "dotenv": "^10.0.0",
    "expo": "^45.0.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~0.9.6",
    "firebase": "9.1.0",
    "formik": "2.1.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "^0.68.2",
    "react-native-gesture-handler": "~2.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "yup": "0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.9.0",
    "babel-preset-expo": "~9.1.0"
  },
  "private": true,
  "version": "1.0.0",
  "name": "my-test-app"
}
`

**Comment by amandeepmittal** [comment]
Thanks @ushyDev for pointing this out. I'll take a look and let you know.

**Comment by ushyDev** [comment]
I got it 😄 
After installing `expo-development-client` I had to move the values from` .env` to the `eas.json` configuration file.

**Comment by amandeepmittal** [comment]
Ah man, that's really awesome that you figured it out :)
