### ISSUE TITLE
Error - Missing package "metro/src/lib/attachWebsocketServer"

### ISSUE THREAD

**Issue by Blake254** [expo-community/expo-firebase-starter#73]
No files were modified from template, this issue occurs when running 'expo start'.

> Starting project at /Users/xxx/Projects_A/FireBaseTemplate
> Developer tools running on http://localhost:19002
> Opening developer tools in the browser...
> Starting Metro Bundler
> Missing package "metro/src/lib/attachWebsocketServer" in the project at: /Users/xxx/Projects_A/FireBaseTemplate
> This usually means `react-native` is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.

**Comment by amandeepmittal** [comment]
Hey @Blake254, sad you got this error. Can you please confirm that you are using the latest version of Expo CLI?

**Comment by amandeepmittal** [comment]
Awesome! Glad you were able to resolve it.
