### ISSUE TITLE
upgrading expo version from 46 to 49

### ISSUE THREAD

**Issue by Roygebrayel** [expo-community/expo-firebase-starter#81]

**Comment by amandeepmittal** [comment]
Hey @Roygebrayel, thanks for opening this issue! This repo has fallen down on maintenance. Will update it to the latest SDK.

**Comment by Roygebrayel** [comment]
that would be great ! good luck

**Comment by axeloehrli** [comment]
hey, just wondering if there's any progress on this issue?

**Comment by deonneon** [comment]
> that would be great ! good luck

> hey, just wondering if there's any progress on this issue?

@Roygebrayel @axeloehrli
I upgraded it to 49 if you guys are interested. There is only one feature loss which is persistence login feature isn't integrated. You will need to upgrade to typescript. I tried to keep this project was pure as possible. 

https://github.com/deonneon/expo-firebase-starter-expo49

@amandeepmittal If you want, I can create a fork version.

**Comment by amandeepmittal** [comment]
@deonneon, a PR is most welcome 🙏

**Comment by Roygebrayel** [comment]
thank you for this work !

**Comment by amandeepmittal** [comment]
This was fixed by #82.
